// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"encoding/json"
)

type Build struct {
	ID       int64
	Project  string
	Meta     json.RawMessage
	Filename string
	Sha512   string
	Mrid     sql.NullString
	Cfid     sql.NullString
}
