// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/mrmelon54/mc-upload-api/database/types"
)

type Build struct {
	ID           int64            `json:"id"`
	Project      string           `json:"project"`
	Meta         *types.BuildMeta `json:"meta"`
	Filename     string           `json:"filename"`
	Sha512       string           `json:"sha512"`
	ModrinthID   string           `json:"modrinth_id"`
	CurseforgeID string           `json:"curseforge_id"`
}
