name: sqlc
on: [ push ]
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.25.0'
      - run: sqlc diff
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrmelon54/migrate-action@v1
        with:
          path: database/migrations
          database: sqlite3://builds.sqlite3.db
          command: up
      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.25.0'
      - run: sqlc vet
